### ISSUE TITLE
Home site

### ISSUE THREAD

**Issue by macebm** [macebm/capstone-project#12]
As a **user** 
I need **a start page** 
so that **the app shows me some information about itself** 

## Home site
![image](https://user-images.githubusercontent.com/72047028/100465560-d1229480-30cf-11eb-8d78-644756e04e23.png)

## Acceptance criteria
- [x] Now the user see first the home page
- [x] The user can switch between store page and home page

## Tasks
- [x] Home component
- [x] React Router / Navigation
- [x] Video component
- [x] Info component
- [x] Add missing style
## Size
medium
