### ISSUE TITLE
Optional Search for a product and get a store

### ISSUE THREAD

**Issue by macebm** [macebm/capstone-project#13]
As a **user** 
I want **to search for a product category** 
so that **all stores that sell a vegan variant are shown** 

## Search page
![image](https://user-images.githubusercontent.com/72047028/100466758-bc470080-30d1-11eb-8ea0-ddcb47f54c4a.png)

## Acceptance criteria
- [ ] The user can search for a product category and gets stores back
- [ ] Every store should be a clickdummy and alert some text
- [ ] First the page should show all stores
- [ ] Care about unvalid input

## Tasks
- [ ] SearchButton component(TDD)
- [ ] Write a test for the button
- [ ] Change the store component
- [ ] Search function
- [ ] Add Endpoint

## Size
large
