### ISSUE TITLE
Technical Setup FE+BE

### ISSUE THREAD

**Issue by macebm** [macebm/capstone-project#2]
## Value statement
As a **developer** 
I need **a good starting point for the project** 
to **create a nice workflow** 

## Description 
Create frontend with create-react-app.
Create backend with symfony.

## Acceptance criteria
- [x] Required extensions installed

## Tasks
- [x] React + Symfony Basic Setup
- [x] Frontend and backend created

## Size
small
