### ISSUE TITLE
Click dummy

### ISSUE THREAD

**Issue by macebm** [macebm/capstone-project#3]
## Value statement
As a **user** 
I need **a click dummy** 
to get **a better impression of the design** 

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/72047028/99966091-1c6a3980-2d96-11eb-9bc5-5bd35bea0464.png)

## Acceptance criteria
- [x] Only need the nav buttons
- [x] Each button should trigger an alert

## Tasks
- [x] Create feature branch
- [x] Create header and footer component
- [x] Create button component
- [x] Add missing styles

## Size
medium
