### ISSUE TITLE
Excel database table

### ISSUE THREAD

**Issue by macebm** [macebm/capstone-project#4]
## Value statement
As **developer**
I need **the data of some products from different stores**
so **I can fill the database with them** 

## Acceptance criteria
- [x] List of all products with manufacturer name and store name
- [x] Milk, cheese and meat divided into categories
- [x] Table with product_shop_relations
- [x] Table with product_manufacturer_relations

## Tasks
- [x] Write down some relevant products in Rewe, Edeka and Denns
- [x] Transfer data to the table
- [x] Edit the relation tables using the collected data

## Size
large
