### ISSUE TITLE
Shop list

### ISSUE THREAD

**Issue by macebm** [macebm/capstone-project#5]
## Value statement - a requirement, not a solution
As a **user** 
I need **a list of all stores** 
so that **no empty page is shown** 

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/72047028/99983193-d4eea800-2dab-11eb-8455-4dcc5cb7bf52.png)

## Acceptance criteria
- [x] Stores loaded from the database

## Tasks
- [x] Write get function
- [x] Create store component

## Size
small
