### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by macebm** [macebm/capstone-project#6]
As a **developer** 
I need **a database with some data** 
so that **the app can fetch real data** 

## You can see the tables in the pdf
[Database.pdf](https://github.com/macebm/capstone-project/files/5608916/Database.pdf)

## Acceptance criteria
- [x] Each entity should contain some data
- [x] At first no end points needed
- [ ] Min one product from each store and category

## Tasks
- [x] Push some data not all datas needed at first
- [x] Store entity 
- [x] Product entity
- [x] Manufacturer entity
- [x] Product_category entity
- [x] Determine and create relations of the entities

## Size
medium
