### ISSUE TITLE
Search for Products

### ISSUE THREAD

**Issue by macebm** [macebm/capstone-project#7]
## Value statement - a requirement, not a solution
As a **user** 
I **would like to be able to search for milk, meat or cheese** 
so that **I am shown stores that offer substitute products** 

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/72047028/99985867-c8b81a00-2dae-11eb-85d3-ee7004ac9319.png)

## Acceptance criteria
- [ ] When the user searches for milk, all stores that offer substitute products will be displayed
- [ ] If the user does not search for anything, he should see all stores

## Tasks
- [ ] Create input component
- [ ] Create search button
- [ ] Write fetch function

## Size
large
