### ISSUE TITLE
Sinlge store details

### ISSUE THREAD

**Issue by macebm** [macebm/capstone-project#8]
As a **user** 
I would **like to see which products a store offers and what they cost** 
so that **I can decide for a store** 

## One store:
![image](https://user-images.githubusercontent.com/72047028/100469205-18ac1f00-30d6-11eb-9c67-0162b660204d.png)

## Acceptance criteria
- [x] After the user clicked on a store in the store site he get a single store with infos
- [x] The user can go back to store or home site
- [x] List of all products sortet by category
- [x] Only products from the shown store
- [x] Products as slides

## Tasks
- [x] SingleStore component
- [x] StoreName component
- [x] Product category component
- [x] Product component
- [x] Add Endpoints
- [x] Fetch some products

## Size
large
